CREATE OR REPLACE FUNCTION SF_GET_TOTAL_COMD_LOCK_AMNT(P_COMD_NAME VARCHAR2)
  RETURN NUMBER AS
  LN_COMD_AMNT INVENTORY_DTLS.AVBL_AMNT%TYPE;
BEGIN
  SELECT SUM(ID.LOCK_AMNT)
    INTO LN_COMD_AMNT
    FROM INVENTORY_DTLS ID, MST_COMMODITY MC
   WHERE ID.COMD_ID = MC.COMD_ID
     AND MC.COMD_NAME = P_COMD_NAME;
  RETURN LN_COMD_AMNT;
END;
/
