CREATE OR REPLACE FUNCTION SF_GET_COMD_ID(P_COMD_NAME VARCHAR2)
RETURN NUMBER
AS
LN_COMD_ID MST_COMMODITY.COMD_ID%TYPE;
BEGIN
SELECT COMD_ID INTO LN_COMD_ID FROM MST_COMMODITY WHERE COMD_NAME = P_COMD_NAME;
RETURN LN_COMD_ID;
END;
/
