CREATE OR REPLACE FUNCTION SF_GET_TOTAL_LOCK_AMNT
RETURN NUMBER
AS
LN_LOCK_AMNT INVENTORY_DTLS.LOCK_AMNT%TYPE;
BEGIN
SELECT SUM(LOCK_AMNT) INTO LN_LOCK_AMNT FROM INVENTORY_DTLS;
RETURN LN_LOCK_AMNT;
END;
/
