CREATE OR REPLACE FUNCTION SF_GET_TOTAL_AVBL_AMNT
RETURN NUMBER
AS
LN_AVBL_AMNT INVENTORY_DTLS.AVBL_AMNT%TYPE;
BEGIN
SELECT SUM(AVBL_AMNT) INTO LN_AVBL_AMNT FROM INVENTORY_DTLS;
--SELECT SUM(NVL(AVBL_AMNT,ASSET_AMNT)) INTO LN_AVBL_AMNT FROM INVENTORY_DTLS;
RETURN LN_AVBL_AMNT;
END;
/
